In [1]:
def details(name, userid, country):
    print('Name :- ', name)
    print('USER ID :- ', userid)
    print('Country :- ', country)
    
details('Hasan', 'hsn01', 'Türkiye')

Name :-  Hasan
USER ID :-  hsn01
Country :-  Türkiye


In [3]:
#Fibonacci
def fibonacci(num):
    if num <= 1:
        return num
    if num == 2:
        return 1
    else:
        return(fibonacci(num - 1) + fibonacci(num - 2))
    
nums = int(input("Kaç tane Fibonacci sayısı üretmek istersiniz? "))

for i in range(nums):
    print(fibonacci(i))

Kaç tane Fibonacci sayısı üretmek istersiniz? 15
0
1
1
2
3
5
8
13
21
34
55
89
144
233
377


In [4]:
#Lambda, Filter, Map, Reduce

In [5]:
#lambda num1, num2 : num1 + num2

In [6]:
addition = lambda a : a + 10
print(addition(5))

15


In [8]:
product = lambda a, b : a * b
print(product(5, 6))

30


In [9]:
addition = lambda a,b,c : a + b + c
print(addition(5,6,2))

13


In [10]:
res = (lambda *args : sum(args))
res(10,20), res(10,20,30,40), res(10,20,30,40,50,60,70)

(30, 100, 280)

In [11]:
res1 = (lambda **kwargs : sum(kwargs.values()))
res1(a = 10, b = 20, c = 30), res1(a = 10, b = 20, c = 30, d = 40, e = 50)

(60, 150)

In [12]:
#filter, filter(function, iterable)

In [13]:
list1 = [1,2,3,4,5,6,7,8,9]

def odd(n):
    if n%2 == 1:
        return True
    else:
        return False

odd_num = list(filter(odd, list1))
odd_num

[1, 3, 5, 7, 9]

In [14]:
list1 = [1,2,3,4,5,6,7,8,9]

odd_num = list(filter(lambda x: x % 2 == 1, list1))
odd_num

[1, 3, 5, 7, 9]

In [ ]:
#map, map(function, iterable)

In [15]:
def twice(n):
    return n*2

doubles = list(map(twice, odd_num))
doubles

[2, 6, 10, 14, 18]

In [16]:
doubles = list(map(lambda n : n*2, odd_num))
doubles

[2, 6, 10, 14, 18]

In [ ]:
#reduce, reduce(function, iterable)

In [17]:
from functools import reduce

In [18]:
def add(a, b):
    return a + b

sum_all = reduce(add, doubles)
sum_all

50

In [20]:
sum_all = reduce(lambda a, b : a + b, doubles)
sum_all

50

In [21]:
sum_all = reduce(lambda a,b:a+b, list(map(lambda n:n*2, list(filter(lambda n:n%2, list1)))))
sum_all

50

In [22]:
import numpy as np

In [23]:
list1 = [10,20,30,40,50,60]
list1

[10, 20, 30, 40, 50, 60]

In [24]:
type(list1)

list

In [25]:
arr1 = np.array(list1)
arr1

array([10, 20, 30, 40, 50, 60])

In [26]:
arr1.data

In [27]:
type(arr1)

numpy.ndarray

In [28]:
arr1.dtype

dtype('int32')

In [29]:
arr1.astype(float)

array([10., 20., 30., 40., 50., 60.])

In [30]:
np.arange(0, 10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [31]:
np.arange(0, 100, 10)

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [32]:
np.arange(100, 10, -10)

array([100,  90,  80,  70,  60,  50,  40,  30,  20])

In [33]:
arr3 = np.arange(0, 10)
arr3.shape

(10,)

In [34]:
arr3.dtype

dtype('int32')

In [35]:
arr3.nbytes

40

In [36]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [37]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [38]:
np.repeat(10, 5)

array([10, 10, 10, 10, 10])

In [39]:
a = np.array([10,20,30])
np.repeat(a, 3)

array([10, 10, 10, 20, 20, 20, 30, 30, 30])

In [40]:
np.full(5, 10)

array([10, 10, 10, 10, 10])

In [41]:
ar1 = np.arange(1, 20)
ar1[ar1 % 2 == 1]

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [42]:
ar1 = np.arange(1, 20)
ar1[ar1 % 2 == 0]

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [43]:
np.linspace(10, 20, 4)

array([10.        , 13.33333333, 16.66666667, 20.        ])

In [44]:
np.linspace(10, 20, 11)

array([10., 11., 12., 13., 14., 15., 16., 17., 18., 19., 20.])

In [45]:
np.random.random(4)

array([0.14307313, 0.35786519, 0.75788085, 0.54952181])

In [46]:
np.random.randint(0, 500, 5)

array([ 44, 379, 248, 161, 391])

In [47]:
np.random.randint(0, 500, 10)

array([248, 117,  80,  95, 117, 288, 447, 429, 101, 424])

In [48]:
np.random.seed(123)
np.random.randint(0, 100, 10)

array([66, 92, 98, 17, 83, 57, 86, 97, 96, 47])

In [49]:
np.random.seed(123)
np.random.randint(0, 100, 10)

array([66, 92, 98, 17, 83, 57, 86, 97, 96, 47])

In [50]:
np.random.seed(101)
np.random.randint(0, 100, 10)

array([95, 11, 81, 70, 63, 87, 75,  9, 77, 40])

In [51]:
np.random.seed(101)
np.random.randint(0, 100, 10)

array([95, 11, 81, 70, 63, 87, 75,  9, 77, 40])

In [52]:
f1 = np.random.uniform(5, 10, size = (10))

In [53]:
f1

array([6.5348311 , 9.4680654 , 8.60771931, 5.94969477, 7.77113796,
       6.76065977, 5.90946201, 8.92800881, 9.82741611, 6.16176831])

In [54]:
np.floor(f1)

array([6., 9., 8., 5., 7., 6., 5., 8., 9., 6.])

In [55]:
np.trunc(f1)

array([6., 9., 8., 5., 7., 6., 5., 8., 9., 6.])

In [56]:
f1.astype(int)

array([6, 9, 8, 5, 7, 6, 5, 8, 9, 6])

In [57]:
b2 = np.random.randn(10) #mean = 0, variance = 1
b2

array([ 0.18869531, -0.75887206, -0.93323722,  0.95505651,  0.19079432,
        1.97875732,  2.60596728,  0.68350889,  0.30266545,  1.69372293])

In [58]:
arr1

array([10, 20, 30, 40, 50, 60])

In [59]:
for index, value in np.ndenumerate(arr1):
    print(index, value)

(0,) 10
(1,) 20
(2,) 30
(3,) 40
(4,) 50
(5,) 60


In [60]:
#Dizi üzerindeki operasyonlar

In [61]:
arr2 = np.arange(1, 20)
arr2

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [62]:
arr2.sum()

190

In [63]:
np.cumsum(arr2)

array([  1,   3,   6,  10,  15,  21,  28,  36,  45,  55,  66,  78,  91,
       105, 120, 136, 153, 171, 190], dtype=int32)

In [64]:
#min(), max(), argmin(), argmax(), mean(), median(), var()

In [65]:
np.std(arr2)

5.477225575051661

In [66]:
#2D dizi işlemleri

In [67]:
A = np.array([[1,2,3,0], [5,6,7,22], [10,11,1,13], [14,15,16,3]])
A

array([[ 1,  2,  3,  0],
       [ 5,  6,  7, 22],
       [10, 11,  1, 13],
       [14, 15, 16,  3]])

In [68]:
A.sum()

129

In [69]:
#max(), min(), mean(), median(), var(), std()

In [70]:
np.amin(A, axis = 0)

array([1, 2, 1, 0])

In [71]:
np.amin(A, axis = 1)

array([0, 5, 1, 3])

In [72]:
for index, value in np.ndenumerate(A):
    print(index, value)

(0, 0) 1
(0, 1) 2
(0, 2) 3
(0, 3) 0
(1, 0) 5
(1, 1) 6
(1, 2) 7
(1, 3) 22
(2, 0) 10
(2, 1) 11
(2, 2) 1
(2, 3) 13
(3, 0) 14
(3, 1) 15
(3, 2) 16
(3, 3) 3


In [73]:
a = np.array([7,5,3,9,0,2])
a[-3]

9

In [74]:
a[1:]

array([5, 3, 9, 0, 2])

In [75]:
#Dizi elemanlarını yer değiştirme

In [77]:
ar = np.arange(1, 20)
ar

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [78]:
rep1 = np.where(ar % 2 == 0, 0, ar)
print(rep1)

[ 1  0  3  0  5  0  7  0  9  0 11  0 13  0 15  0 17  0 19]


In [79]:
ar2 = np.array([10,20,30,10,10,20,20])
rep2 = np.where(ar2 == 10, 99, ar2)
print(rep2)

[99 20 30 99 99 20 20]


In [80]:
p2 = np.arange(0, 100, 10)
p2

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [81]:
np.put(p2, [0,3,5], [33,55,99])
p2

array([33, 10, 20, 55, 40, 99, 60, 70, 80, 90])

In [82]:
#Eksik değerler (İng. missing values) ile ilgilenme

In [83]:
a = np.array([10, np.nan, 20, 30, 60, np.nan, 90, np.inf])
a

array([10., nan, 20., 30., 60., nan, 90., inf])

In [84]:
np.isnan(a)

array([False,  True, False, False, False,  True, False, False])

In [85]:
np.where(np.isnan(a))

(array([1, 5], dtype=int64),)

In [86]:
a[np.isnan(a)] = 99

In [87]:
a

array([10., 99., 20., 30., 60., 99., 90., inf])

In [88]:
np.isnan(a).any()

False

In [89]:
A = np.array([[1,2,np.nan,4],[np.nan,6,7,8], [10, np.nan, 12, 13], [14,15,16,17]])
A

array([[ 1.,  2., nan,  4.],
       [nan,  6.,  7.,  8.],
       [10., nan, 12., 13.],
       [14., 15., 16., 17.]])

In [90]:
np.isnan(A)

array([[False, False,  True, False],
       [ True, False, False, False],
       [False,  True, False, False],
       [False, False, False, False]])

In [91]:
np.where(np.isnan(A))

(array([0, 1, 2], dtype=int64), array([2, 0, 1], dtype=int64))

In [92]:
#Dizileri Yatay ve Dikey olarak Birleştirme

In [93]:
a = np.zeros(20).reshape(2, -1)
b = np.repeat(1, 20).reshape(2, -1)
a

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [94]:
b

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])

In [95]:
np.vstack([a,b])

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [96]:
np.hstack([a, b])

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1.]])